name: TGSoul
version: '${project.version}'
main: com.tgsoul.TGSoulPlugin
api-version: '1.20'
authors: [Prabin (TG)]
description: A comprehensive soul system plugin for Minecraft.
Check out our YouTube: www.youtube.com/@TechinpointGamerz
website: https://techinpointgamerz.netlify.app

softdepend: [Geyser]

commands:
  soul:
    description: Main soul command
    usage: /<command> [help|recipe|give|take|set|get|unban|reload|top|stats|pack] [player|amount]
    permission: tgsoul.use
    aliases: [souls]
  soulwithdraw:
    description: Withdraw a soul as an item
    usage: /<command>
    permission: tgsoul.withdraw
    aliases: [sw]

permissions:
  tgsoul.*:
    description: All TGSoul permissions
    children:
      tgsoul.use: true
      tgsoul.withdraw: true
      tgsoul.admin: true
  tgsoul.use:
    description: Basic soul commands
    default: true
  tgsoul.withdraw:
    description: Withdraw souls as items
    default: true
  tgsoul.admin:
    description: Admin soul commands
    default: op
    children:
      tgsoul.use: true
      tgsoul.withdraw: true